### ISSUE TITLE
Crashing when execution is finished

### ISSUE THREAD

**Issue by joeyballentine** [media2x/waifu2x-ncnn-vulkan-python#1]
Posting this here as the issue in the realsr repo got closed.

The new prerelease build works for me and produces an output. However, my python crashes when the execution is finished.

Attaching a VS debugger to it when it crashes produces this error:

> Unhandled exception at 0x0000000000000000 in python.exe: 0xC0000005: Access violation executing location 0x0000000000000000.

According to this [StackOverflow post](https://stackoverflow.com/questions/10478941/0xc0000005-access-violation-reading-location-0x00000000), it appears to be related to the c++ code somehow. Do you have any idea why this could be happening? I'm on Windows 11 and python 3.9 -- however someone else I know who is also using 11 and 3.9 does not have this issue.

[This post ](https://social.msdn.microsoft.com/Forums/vstudio/en-US/e90739ca-6ced-4e07-b0af-0cfef6289dc6/access-violation-reading-location-0x0000000000000000?forum=vcgeneral)also states that it has to do with trying to read a null pointer

**Comment by joeyballentine** [comment]
Interestingly, it does not crash when I run it in CPU mode. This leads me to think that it is specific to GPU/Vulkan processing, and since it still produces a proper output it probably is happening during some sort of garbage collection or cleanup function

**Comment by ArchieMeng** [comment]
Could you try to upgrade your graphics card driver or use another device with a different GPU to run the program?
This is a known issue that was found at the very beginning of the development.
https://github.com/Tencent/ncnn/issues/2666

**Comment by joeyballentine** [comment]
I'm on the latest Nvidia drivers. I can try on my laptop that has a 1050 in it (my main PC has a 3070ti). I'll let you know what happens with that

**Comment by joeyballentine** [comment]
It works fine on my laptop, interestingly enough

**Comment by ArchieMeng** [comment]
> 

Thanks for your report.
So, it is clear that this problem is a device / driver related problem.
My RTX 2060 and GTX 1050Ti used to have such problems, however, one day, they started to work fine.

**Comment by joeyballentine** [comment]
After taking a look at the ncnn code for this function:

```void destroy_gpu_instance()
{
    MutexLockGuard lock(g_instance_lock);

    if ((VkInstance)g_instance == 0)
        return;

    // NCNN_LOGE("destroy_gpu_instance");

    glslang::FinalizeProcess();

    for (int i = 0; i < NCNN_MAX_GPU_COUNT; i++)
    {
        delete g_default_vkdev[i];
        g_default_vkdev[i] = 0;

        delete g_gpu_infos[i];
        g_gpu_infos[i] = 0;
    }

#if ENABLE_VALIDATION_LAYER
    if (support_VK_EXT_debug_utils)
    {
        DestroyDebugUtilsMessengerEXT(g_instance, g_instance.callback, NULL);
        g_instance.callback = 0;
    }
#endif // ENABLE_VALIDATION_LAYER

    vkDestroyInstance(g_instance, 0);

    g_instance.instance = 0;
}
```

My guess is the crash is happening due to this section:
```    for (int i = 0; i < NCNN_MAX_GPU_COUNT; i++)
    {
        delete g_default_vkdev[i];
        g_default_vkdev[i] = 0;

        delete g_gpu_infos[i];
        g_gpu_infos[i] = 0;
    }
```
    
I do not know C++ that well, but wouldn't it be the case that you're freeing the memory associated with each of those items at the array index, but then trying to access those items which no longer exist in memory in order to set them to 0?

My guess is if you remove that setting to 0 the crash will no longer occur.

**Comment by joeyballentine** [comment]
Ignore me, I've been informed this is not how C++ works and that it should be setting it to zero
