### ISSUE TITLE
Failed building wheel for waifu2x-ncnn-vulkan-python

### ISSUE THREAD

**Issue by lianyun0502** [media2x/waifu2x-ncnn-vulkan-python#2]
Hi,

I have a problem about like this error when i use command "pip install waifu2x-ncnn-vulkan-python".Do you have any idea?

ERROR: Failed building wheel for waifu2x-ncnn-vulkan-python
Failed to build waifu2x-ncnn-vulkan-python
ERROR: Could not build wheels for waifu2x-ncnn-vulkan-python, which is required to install pyproject.toml-based projects

Environment is window 11 , python 3.7 with IDE pycharm.

**Comment by ArchieMeng** [comment]
It looks like a dependency problem with pyproject.toml . Could you try installing it alone or just installing waifu2x-ncnn-vulkan-python in a virtualenv in terminal?

**Comment by ArchieMeng** [comment]
Closed for not receiving further updates. Reopen it if the problem still exist.
